# Generated by Django 5.2.9 on 2025-12-12 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='练习标题')),
                ('content_url', models.URLField(verbose_name='文章链接')),
                ('order', models.IntegerField(default=1, help_text='数字越小排越前', verbose_name='排序')),
            ],
            options={
                'verbose_name': '练习项目',
                'verbose_name_plural': '练习项目',
            },
        ),
        migrations.CreateModel(
            name='PracticeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_audio', models.FileField(upload_to='student_audios/', verbose_name='学员录音')),
                ('submitted_at', models.DateTimeField(auto_now=True, verbose_name='提交时间')),
                ('teacher_comment_text', models.TextField(blank=True, null=True, verbose_name='老师文字点评')),
                ('teacher_comment_audio', models.FileField(blank=True, null=True, upload_to='teacher_audios/', verbose_name='老师语音点评')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='点评时间')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.exercise', verbose_name='练习项目')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='学员')),
            ],
            options={
                'verbose_name': '练习记录',
                'verbose_name_plural': '练习记录',
            },
        ),
    ]
