# Generated by Django 5.2.9 on 2025-12-12 07:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='练习图文内容'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='demo_audio',
            field=models.FileField(blank=True, help_text='可选：上传老师的示范录音', null=True, upload_to='exercise_demos/', verbose_name='示范音频'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='content_url',
            field=models.URLField(blank=True, null=True, verbose_name='原文链接'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='order',
            field=models.IntegerField(default=1, verbose_name='排序'),
        ),
    ]
