# Generated by Django 5.2.9 on 2025-12-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0002_exercise_content_exercise_demo_audio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="practicerecord",
            name="feedback",
            field=models.TextField(blank=True, null=True, verbose_name="老师点评"),
        ),
    ]
