# Generated by Django 5.2.9 on 2025-12-14 23:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0003_practicerecord_feedback"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="practicerecord",
            options={"verbose_name": "单条录音", "verbose_name_plural": "单条录音"},
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="content_url",
        ),
        migrations.RemoveField(
            model_name="practicerecord",
            name="feedback",
        ),
        migrations.RemoveField(
            model_name="practicerecord",
            name="reviewed_at",
        ),
        migrations.AlterField(
            model_name="exercise",
            name="demo_audio",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="exercise_demos/",
                verbose_name="示范音频",
            ),
        ),
        migrations.AlterField(
            model_name="practicerecord",
            name="teacher_comment_audio",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="teacher_audios/",
                verbose_name="语音点评",
            ),
        ),
        migrations.AlterField(
            model_name="practicerecord",
            name="teacher_comment_text",
            field=models.TextField(blank=True, null=True, verbose_name="单句点评"),
        ),
        migrations.CreateModel(
            name="DailyCheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="打卡日期"
                    ),
                ),
                (
                    "is_submitted",
                    models.BooleanField(default=False, verbose_name="是否已提交"),
                ),
                (
                    "teacher_summary",
                    models.TextField(
                        blank=True, null=True, verbose_name="老师今日总评"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学员",
                    ),
                ),
            ],
            options={
                "verbose_name": "每日打卡(作业本)",
                "verbose_name_plural": "每日打卡(作业本)",
                "unique_together": {("student", "date")},
            },
        ),
        migrations.AddField(
            model_name="practicerecord",
            name="daily_checkin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="training.dailycheckin",
                verbose_name="所属打卡",
            ),
        ),
    ]
