# Generated by Django 5.2.9 on 2025-12-15 23:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0004_alter_practicerecord_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dailycheckin",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_checkins",
                to=settings.AUTH_USER_MODEL,
                verbose_name="点赞用户",
            ),
        ),
        migrations.AddField(
            model_name="dailycheckin",
            name="teacher_audio",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="teacher_summary/%Y/%m/",
                verbose_name="老师语音总评",
            ),
        ),
        migrations.AlterField(
            model_name="dailycheckin",
            name="teacher_summary",
            field=models.TextField(blank=True, null=True, verbose_name="老师文字总评"),
        ),
    ]
