# Generated by Django 5.2.9 on 2025-12-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0005_dailycheckin_likes_dailycheckin_teacher_audio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="practicerecord",
            name="student_audio",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="student_audios/",
                verbose_name="学员录音",
            ),
        ),
    ]
