# Generated by Django 5.2.9 on 2025-12-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_announcement_readrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='announcement_audios/%Y/%m/', verbose_name='语音通知'),
        ),
    ]
