# Generated by Django 5.2.9 on 2025-12-30 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_announcement_audio_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='成就名称')),
                ('description', models.TextField(verbose_name='成就描述')),
                ('icon', models.CharField(default='🏆', max_length=50, verbose_name='图标')),
                ('condition_type', models.CharField(choices=[('streak', '连续天数'), ('total_days', '累计天数'), ('exp', '经验值'), ('recordings', '录音数量'), ('level', '等级'), ('first', '首次完成')], max_length=50, verbose_name='条件类型')),
                ('condition_value', models.IntegerField(default=1, verbose_name='条件值')),
                ('exp_reward', models.IntegerField(default=50, verbose_name='经验奖励')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '成就',
                'verbose_name_plural': '成就',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BuddyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='配对时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('student_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_as_a', to=settings.AUTH_USER_MODEL, verbose_name='学员A')),
                ('student_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_as_b', to=settings.AUTH_USER_MODEL, verbose_name='学员B')),
            ],
            options={
                'verbose_name': '互帮配对',
                'verbose_name_plural': '互帮配对',
            },
        ),
        migrations.CreateModel(
            name='Encouragement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500, verbose_name='鼓励消息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encouragements', to='training.buddypair', verbose_name='配对')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
            ],
            options={
                'verbose_name': '鼓励消息',
                'verbose_name_plural': '鼓励消息',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_points', models.IntegerField(default=0, verbose_name='经验值')),
                ('level', models.IntegerField(default=1, verbose_name='等级')),
                ('streak_days', models.IntegerField(default=0, verbose_name='连续练习天数')),
                ('last_practice_date', models.DateField(blank=True, null=True, verbose_name='上次练习日期')),
                ('total_practice_days', models.IntegerField(default=0, verbose_name='累计练习天数')),
                ('total_recordings', models.IntegerField(default=0, verbose_name='累计录音数')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学员档案',
                'verbose_name_plural': '学员档案',
            },
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='获得时间')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.achievement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学员成就',
                'verbose_name_plural': '学员成就',
                'unique_together': {('student', 'achievement')},
            },
        ),
    ]
