# Generated by Django 5.2.9 on 2026-01-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_achievement_buddypair_encouragement_studentprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_advanced',
            field=models.BooleanField(default=False, help_text='勾选后此练习不计入每日打卡，但仍给经验值', verbose_name='进阶练习'),
        ),
    ]
